name: "Application Deploy"

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
  pull_request:
    paths:
      - 'app/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        working-directory: ./app
        
      - name: Build and push container
        run: |
          docker build -t ${{ secrets.ACR_SERVER }}/demo-app:${{ github.sha }} .
          docker push ${{ secrets.ACR_SERVER }}/demo-app:${{ github.sha }}
        working-directory: ./app
